on:
  workflow_call:
    inputs:
      nothing:
        type: boolean
        default: true

jobs:
  deploy:
    uses: ./.github/workflows/wc-cd-01-deploy.yaml
    name: "ğŸ› ï¸"
    secrets: inherit
